#!/bin/bash

here=$(pwd)

for i in $(ls); do
	if [[ -d ${i} ]]; then
		cd ${i}
		for j in $(ls); do
			if [[ -d ${j} ]]; then
				cd ${j}
				[[ -f "metadata.xml" ]] || cp ${here}/metadata.xml.example $(pwd) -v
				cd ..
			else
				echo just a file...
			fi
		done
		cd ..
	else
		echo just a file..
	fi
done
