#!/bin/bash

here=$(pwd)

for i in $(ls); do
	[[ -d ${i} ]] || continue
	cd ${i}
	for j in $(ls); do
		[[ -d ${j} ]] || continue
		cd ${j}
		[[ -f "metadata.xml" ]] || cp ${here}/metadata.xml.example $(pwd) -v
		cd ..
	done
	cd ..
done
