name: Test ebuilds in Docker container

on:
  # ebuild installation tests can take very long time, so run tests nightly
  schedule:
    - cron: '0 0 * * *'
  # Allow tests to be triggered manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - uses: ./.github/actions/run-test-script
      with:
        script: ./tests/run.sh
