name: Scan ebuilds with pkgcheck

on:
  push:
  pull_request:
  schedule:
    # Run tests every day to capture changes in ::gentoo that affects ebuilds
    # in this overlay as soon as possible
    - cron: '0 0 * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Switch back to pkgcore/pkgcheck-action@v1 after this issue is resolved:
    # https://github.com/pkgcore/pkgcheck-action/issues/4
    - name: Run pkgcheck
      uses: nabbi/pkgcheck-action@v1
