name: "Scan ebuilds with pkgcheck"

on:
  push:
  pull_request:
  schedule:
    # Run tests every day to capture changes in ::gentoo that affects ebuilds
    # in this overlay as soon as possible
    - cron: '0 0 * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Run pkgcheck"
        uses: pkgcore/pkgcheck-action@v1
