name: Scan ebuilds with repoman

on:
  push:
  pull_request:
  schedule:
    # Run tests every day to capture changes in ::gentoo that affects ebuilds
    # in this overlay as soon as possible
    - cron: '0 0 * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up master ::gentoo
        run: |
          ./.github/workflow-scripts/setup-master-gentoo.sh
      - name: Set up repoman
        run: |
          ./.github/workflow-scripts/setup-portage.sh repoman
      - name: Run repoman
        run: |
          repoman -dx full
